name: Deploy to S3

# Define when this workflow will run
on:
  push:
    branches:
      - main

#Define the deployment job
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Define the steps in the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Name: Sync files to S3
      - name: Sync files to S3
        run: aws s3 sync . s3://${{ secrets.S3_connerbartels.com }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1